// export default {
//     'login': 'login',
//     'register': 'user/register',
//     'sendCaptcha': 'user/sendCaptcha',
//     'getUserInfo': 'user/info',
//     'isLogin': 'isLogin',
//     'logout': 'logout',
//     'cityList': 'area/city',
//     'areaList': 'area',
//     'addressList': 'address/list',
//     'addAddress': 'address/save',
//     'delAddress': 'address/del',
//     'checkoutOrder': 'order/checkout',
//     'orderList': 'order/list',
//     'checkOrder': 'order/check',
//     'cancelOrder': 'order/cancel',
//     'payOrder': 'payment',
//     'getQRImg': 'payment/qr',
//     'checkWechatOrder': 'payment/check'
// }